### ISSUE TITLE
namespace was create after objects in namespace

### ISSUE THREAD

**Issue by sbldocker** [hashicorp/terraform-provider-kubernetes-alpha#80] opened 2020-06-28 15:05 UTC
### Terraform Version and Provider Version

Terraform v0.12.28
+ provider.kubernetes-alpha (unversioned) it is  0.1.0 for linux amd64

### Terraform Configuration Files
```hcl
provider "kubernetes-alpha" {
  config_path = "~/.kube/config" // path to kubeconfig
}

variable "registry_server" {
  type = string
  default = "192.168.1.39:5000"
}

variable "connex_version" {
    type = string
    default = "latest"
}


locals {
  connex_image = "${var.registry_server}/connex:${var.connex_version}"
  owner        = "Community Team"
}


resource "kubernetes_manifest" "connex-namespace" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "v1"
    "kind" = "Namespace"
    "metadata" = {
      "name" = "connex-env"
      "labels" = {
        "istio-injection" = "enabled"
      }
    }
  }
}


resource "kubernetes_manifest" "connex-service" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "v1"
    "kind" = "Service"
    "metadata" = {
      "name" = "connex-srv"
      "namespace" = "connex-env"
      "labels" = {
        "app" = "connex-srv"
      }
    }
    spec = {
      "ports" = [
        {
          "port" = 8080
          "protocol" = "TCP"
        }
      ]
      "selector" = {
        "app" =  "connex-srv"
      }
      "type" =  "ClusterIP"
    }
  }
}

resource "kubernetes_manifest" "connex-service-account" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "v1"
    "kind" = "ServiceAccount"
    "metadata" = {
      "name" = "connex-srv"
      "namespace" = "connex-env"
      "labels" = {
        "app" = "connex-srv"
      }
    }
  }
}


resource "kubernetes_manifest" "connex-deployment" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "apps/v1"
    "kind" = "Deployment"
    "metadata" = {
      "name" = "connex-srv"
      "namespace" = "connex-env"
      "labels" = {
        "app" = "connex-srv"
      }
    }
    spec = {
      "selector" = {
        "matchLabels" = {
          "app" =  "connex-srv"
        }
      }
      "replicas" = 1
      "template" = {
        "metadata" = {
          "labels" = {
            "app" = "connex-srv"
            "version" = var.connex_version
          }
        }
        spec = {
          "serviceAccountName" = "connex-srv"
          "containers" = [
            {
              "name" = "connex-pod"
              "image" = local.connex_image
              "ports" = [
                {
                  "containerPort" = 8080
                  "protocol" = "TCP"
                }
              ]
            }
          ]
        }
      }
    }
  }
}

```

### Expected Behavior
What should have happened?
First create the namespace, than create all objects in the namespace.

### Actual Behavior
Actual the objects were not create, because of missing namespace
```
Error: rpc error: code = Unknown desc = update dry-run for 'connex-env/connex-srv' failed: namespaces "connex-env" not found
Error: rpc error: code = Unknown desc = update dry-run for 'connex-env/connex-srv' failed: namespaces "connex-env" not found
Error: rpc error: code = Unknown desc = update dry-run for 'connex-env/connex-srv' failed: namespaces "connex-env" not found
```

### Important Factoids
using standard kubernetes installation 1 master 2 workers with istio and metallb

**Comment by martin-schaefer** [comment] 2020-07-17 16:48
I have exactly the same issue. I am using kubernetes alpha provider version 0.1.0:

Error: rpc error: code = Unknown desc = update dry-run for 'apps/namespace-reader' failed: namespaces "apps" not found
Error: rpc error: code = Unknown desc = update dry-run for 'apps/k8s-bff' failed: namespaces "apps" not found
Error: rpc error: code = Unknown desc = update dry-run for 'apps/k8s-sba' failed: namespaces "apps" not found

**Comment by blucas** [comment] 2020-07-22 21:45
Is this a problem because you are assuming the provider should know there is a dependency between the `resource` blocks?

Given that you are managing the namespace and associated resources why not just reference the dependency explicitly like so:
```hcl
resource "kubernetes_manifest" "connex-namespace" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "v1"
    "kind" = "Namespace"
    "metadata" = {
      "name" = "connex-env"
      "labels" = {
        "istio-injection" = "enabled"
      }
    }
  }
}

resource "kubernetes_manifest" "connex-service-account" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "v1"
    "kind" = "ServiceAccount"
    "metadata" = {
      "name" = "connex-srv"
      "namespace" = kubernetes_manifest.connex-namespace.metadata.name
      "labels" = {
        "app" = "connex-srv"
      }
    }
  }
}
```

**Comment by alexsomesan** [comment] 2020-07-24 02:55
Unfortunately this is a known limitation (described in the introductory blog post: https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform under "Current Limitations").

It should be resolved when #41 is merged.

**Comment by dak1n1** [comment] 2020-10-12 21:22
Closing this issue as a duplicate of #57

**Closed by dak1n1** 2020-10-12 21:22 UTC
Labels: bug

**Comment by phlegx** [comment] 2020-11-10 14:01
@alexsomesan May I ask, if there is some progress in this? Happening to me too.
