### ISSUE TITLE
Provider crashes when being referenced early

### ISSUE THREAD

**Issue by HighwayofLife** [hashicorp/terraform-provider-kubernetes-alpha#97] opened 2020-08-18 20:55 UTC
In my configuration, I'm using the Helm provider to create the CRD and then the kubernetes-alpha provider to create the resource that is part of the CRD, so it has a depends on for that helm release, but it appears that it's causing Terraform to crash to use it this way.

### Terraform Version and Provider Version
Terraform 0.12.28
```
* provider.azurerm: version = "~> 2.22"
* provider.helm: version = "~> 1.2"
* provider.kubernetes: version = "~> 1.12"
* provider.kubernetes-alpha: version = "~> 0.1"
```

### Kubernetes Version

K8s Rev: v1.17.6

### Affected Resource(s)

- kubernetes_manifest.cluster-secret

### Terraform Configuration Files
```hcl
data "azurerm_key_vault" "vault" {
  name                = var.key_vault_name
  resource_group_name = var.key_vault_resource_group_name
}

data "azurerm_key_vault_secret" "secrets_store_creds" {
  name         = var.secrets_store_creds.secret_name
  key_vault_id = data.azurerm_key_vault.vault.id
}

data "azurerm_key_vault_secret" "client_cert" {
  name         = "${var.cluster_name}-client-cert"
  key_vault_id = data.azurerm_key_vault.vault.id
}

data "azurerm_key_vault_secret" "client_key" {
  name         = "${var.cluster_name}-client-key"
  key_vault_id = data.azurerm_key_vault.vault.id
}

data "azurerm_key_vault_secret" "ca_cert" {
  name         = "${var.cluster_name}-ca-cert"
  key_vault_id = data.azurerm_key_vault.vault.id
}

provider "kubernetes" {
  host             = "https://${var.kube_api_endpoint}"
  load_config_file = "false"

  client_certificate     = data.azurerm_key_vault_secret.client_cert.value
  client_key             = data.azurerm_key_vault_secret.client_key.value
  cluster_ca_certificate = data.azurerm_key_vault_secret.ca_cert.value
}

provider "kubernetes-alpha" {
  host = "https://${var.kube_api_endpoint}"

  client_certificate     = data.azurerm_key_vault_secret.client_cert.value
  client_key             = data.azurerm_key_vault_secret.client_key.value
  cluster_ca_certificate = data.azurerm_key_vault_secret.ca_cert.value
}

provider "helm" {
  kubernetes {
    host             = "https://${var.kube_api_endpoint}"
    load_config_file = "false"

    client_certificate     = data.azurerm_key_vault_secret.client_cert.value
    client_key             = data.azurerm_key_vault_secret.client_key.value
    cluster_ca_certificate = data.azurerm_key_vault_secret.ca_cert.value
  }
}

locals {
  cluster_secret_namespace = "cluster-secret"
}

resource "kubernetes_namespace" "cluster-secret" {
  metadata {
    name = local.cluster_secret_namespace

    labels = {
      name = local.cluster_secret_namespace
    }
  }

  lifecycle {
    ignore_changes = all
  }
}

# https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/service-principal-mode.md
resource "kubernetes_secret" "secrets-store-creds" {
  metadata {
    name      = "secrets-store-creds"
    namespace = local.cluster_secret_namespace
  }

  type = "Opaque"

  data = {
    "clientid"     = var.secrets_store_creds.client_id
    "clientsecret" = data.azurerm_key_vault_secret.secrets_store_creds.value
  }

  depends_on = [
    kubernetes_namespace.cluster-secret
  ]
}

resource "helm_release" "cluster-secret" {
  name      = "cluster-secret"
  chart     = "${var.chart_root}/cluster-secret"
  namespace = local.cluster_secret_namespace

  values = [
    "${file("${var.chart_root}/cluster-secret/values.yaml")}"
  ]

  depends_on = [
    kubernetes_namespace.cluster-secret
  ]
}

resource "kubernetes_manifest" "cluster-secret" {
  provider = kubernetes-alpha

  manifest = {
    apiVersion = "clustersecret.io/v1"
    kind       = "ClusterSecret"
    metadata = {
      name = "global-keyvault-spn"
    }

    data = {
      "clientid"     = var.secrets_store_creds.client_id
      "clientsecret" = data.azurerm_key_vault_secret.secrets_store_creds.value
    }
  }

  depends_on = [
    helm_release.cluster-secret
  ]
}
```

### Debug / Panic Output
https://gist.github.com/HighwayofLife/6128161f0970ef9e780bb1a6aa1a9856

### Expected Behavior
Terraform should have generated a plan with the resource to be created in Kubernetes.

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
1. `terraform plan`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by HighwayofLife** [comment] 2020-08-19 01:46
After further testing, this doesn't have anything to do with depends on, and is entirely related to the provider configuration and being referenced to early??? ... related to #89

**Comment by briantopping** [comment] 2020-10-24 22:05
I still find that `depends_on` doesn't work though. Creating a resource in a namespace where the namespace needs to be created fails that the resource can't find it:
```
resource "kubernetes_namespace" "example" {
  provider = kubernetes-alpha
  metadata {
    name = var.vm_namespace
  }
}

resource "kubernetes_manifest" "something" {
  provider = kubernetes-alpha
  depends_on = [kubernetes_namespace.example]
  manifest = {
    "metadata" = {
      "name" = var.image_name
      "namespace" = var.vm_namespace
    ...
    }
  }
}
```

**Comment by aareet** [comment] 2020-11-04 22:40
@HighwayofLife if the issue is not related to the depends on, can you please update the title/description to reflect what the current issue is?

**Comment by HighwayofLife** [comment] 2020-11-05 16:19
I updated the title, it looks like #92 might have fixed this issue.

**Comment by aareet** [comment] 2020-11-05 17:19
@HighwayofLife can you retest with https://github.com/hashicorp/terraform-provider-kubernetes-alpha/releases/tag/v0.2.1? #92 was shipped with that version

**Comment by aareet** [comment] 2021-01-25 23:05
Closing since it has been about 3 months

**Closed by aareet** 2021-01-25 23:05 UTC
Labels: bug, waiting-response
