### ISSUE TITLE
Support discrete credentials in provider configuration.

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-provider-kubernetes-alpha#4] opened 2020-04-23 21:59 UTC
### Expected Behavior
The provider should accept discrete credentials (e.g. client certificates / username & password / token) as well as custom API endpoints and cluster certificate authorities.
It should also support Kubernetes client auth plugins.

### Actual Behavior
The provider now only sources configuration from a Kubeconfig file. This is an artefact of the early development cycle and does not fully cover users' needs.

## Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BarnumD** [comment] 2020-06-02 12:15
In the mean time, Is there a way to provide the kube config file in the terraform cloud environment?  I tried the following, but get an error.
```
resource "local_file" "kube_config" {
    content     = data.azurerm_kubernetes_cluster.aks.kube_admin_config_raw
    filename = "./config"
}

provider "kubernetes-alpha" {
  server_side_planning = true
  alias                  = "aks"
  config_file          = local_file.kube_config.filename
}
```
`Error: rpc error: code = Unavailable desc = transport is closing`

Also tried:  `config_file          =  "./config"` , but this says `./config: no such file or directory`.  I think because the provider is evaluated first.

**Comment by dak1n1** [comment] 2020-06-03 17:50
One way I've been working around this issue is to use two separate `terraform apply`s. That is, one terraform config to create the kubeconfig, and another to utilize that kubeconfig. I have an example of this in progress here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/49 (though it is not specific to TFC).

**Comment by BarnumD** [comment] 2020-06-11 20:13
I see that this was closed, but I built a binary based on the new code and still get the following errors.  What else am I missing?
```
provider "kubernetes-alpha" {
  server_side_planning = true
  alias                  = "aks"
  host                   = data.azurerm_kubernetes_cluster.aks.kube_admin_config.0.host
  username               = data.azurerm_kubernetes_cluster.aks.kube_config.0.username
  password               = data.azurerm_kubernetes_cluster.aks.kube_config.0.password
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.aks.kube_admin_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.aks.kube_admin_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.aks.kube_admin_config.0.cluster_ca_certificate)
}
```
```
An argument named "host" is not expected here.
An argument named "username" is not expected here.
An argument named "password" is not expected here.
An argument named "client_certificate" is not expected here.
An argument named "client_key" is not expected here.
An argument named "cluster_ca_certificate" is not expected here.
```

**Comment by jcmcken** [comment] 2020-06-25 14:39
Same issue as @BarnumD. The latest release doesn't allow any of those arguments to the provider. It also seems like there hasn't been a "nightly" release in 14 days. Can we re-open this?

**Comment by aareet** [comment] 2020-06-25 17:06
I was able to reproduce https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/4#issuecomment-642904041 with the latest master build as well

**Comment by aareet** [comment] 2020-06-25 17:39
My mistake, it turns out I had an old binary in my plugins folder. I was able to supply username/password pair to the provider with a current local build of the provider based off the master branch. @BarnumD can you check if you have any old binaries in your terraform.d/plugins folder that might be discovered by terraform instead of the latest build?

**Comment by aareet** [comment] 2020-06-25 17:40
@jcmcken we've stopped doing the nightly releases and are working to fix the release to push out the next build in #68

**Comment by BarnumD** [comment] 2020-06-25 20:44
It could be.  I had renamed the old copy of the provider to `.old` thinking that would do it.  Now, I've moved both and built a new copy of the provider with `make install` and then copied that file over to my code repository.  However, now I'm getting this strange error `Error: rpc error: code = Canceled desc = context canceled`.

**Comment by dak1n1** [comment] 2020-10-12 19:36
It looks like the two associated PRs for this have merged, so I'll go ahead and close it. Please re-open if it's still an issue, thanks.

**Closed by dak1n1** 2020-10-12 19:36 UTC
Labels: enhancement, waiting-response
