### ISSUE TITLE
Data source: generic Kubernetes objects

### ISSUE THREAD

**Issue by mariadb-JeffBachtel** [hashicorp/terraform-provider-kubernetes-alpha#131] opened 2020-10-29 22:50 UTC
### Description

A `data` source that was able to refer to arbitrary (including custom) Kubernetes resource objects would be nice

### Potential Terraform Configuration

```hcl
data "kubernetes_object" "my_services" {
  kind = "Service"
  selector {
    app = "foo"
  }
}

locals {
  my_service_fqdn = data.kubernetes_object.my_services[0].status.load_balancer.ingress[0].hostname
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment] 2020-11-12 20:26
Thanks for opening this issue! We actually have plans to create a data source like this already. I'll close this issue as a duplicate of https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/25

**Closed** 2020-11-12 21:01 UTC
Labels: enhancement
