### ISSUE TITLE
Changes to immutable fields not applined when resource is tainted

### ISSUE THREAD

**Issue by cyberjacob** [hashicorp/terraform-provider-kubernetes-alpha#132] opened 2020-11-06 20:00 UTC
### Terraform Version and Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.1

### Kubernetes Version

Client Version: 1.18.2
Server Version: 1.19.3

### Affected Resource(s)
I found this with a Service, but likely affecting other resources

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "service" {
        provider = kubernetes-alpha

        manifest = {
                apiVersion = "v1"
                kind = "Service"
                metadata = {
                        name = "test-service"
                        namespace = "test-namespace"
                }

                spec = {
                        "ipFamily" = "IPv6"
                        loadBalancerIP = "2001:678:xxx:xxx::120"
                        clusterIP = "2001:678:xxx:xxx::120"
                        ports = [{
                                port = 80
                                protocol = "TCP"
                                targetPort = 80
                        }]

                        selector = {
                                deployment = "testapp"
                        }
                        type = "LoadBalancer"
                }
        }
}
```

### Debug Output
https://gist.github.com/cyberjacob/748a09b9b8c660c450fdbe5c0b4548df

### Panic Output
None

### Expected Behavior
As the resource is tainted, expected for it to be deleted and recreated.

### Actual Behavior
The following error is recieved
Error: rpc error: code = Unknown desc = update dry-run for 'test-namespace/test-service' failed: Service "test-service" is invalid: spec.clusterIP: Invalid value: "2001:678:xxx:xxx::120": field is immutable

### Steps to Reproduce
1. `terraform apply

### Important Factoids
loadBalancerIP and clusterIP were previously explicitly set to different values within the same subnet

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment] 2020-11-09 18:10
Thanks for this bug report! I was able to reproduce this using the latest build from master today. Here's how I reproduced it in minikube (this is mostly information to help my team debug):

```
provider "kubernetes-alpha" {
  config_path = "/home/dakini/.kube/config"
  server_side_planning = true
}

resource "kubernetes_manifest" "service" {
        provider = kubernetes-alpha

        manifest = {
                apiVersion = "v1"
                kind = "Service"
                metadata = {
                        name = "test-service"
                        namespace = "default"
                }

                spec = {
                        loadBalancerIP = "10.96.3.5"
                        clusterIP = "10.96.3.11"
                        ports = [{
                                nodePort = 32750
                                port = 80
                                protocol = "TCP"
                                targetPort = 80
                        }]

                        selector = {
                                deployment = "testapp"
                        }
                        type = "LoadBalancer"
                }
        }
}
```

First, `terraform apply` this config. Then change the value of the `clusterIP` field and try to apply. It will say it's immutable.

Then `terraform taint kubernetes_manifest.service` and attempt the apply again. It should have replaced the resource, but instead it gives the error about the immutable field.

I also tried with `server_side_planning = false`, but that one gives a different error.

```
kubernetes_manifest.service: Refreshing state...
kubernetes_manifest.service: Destroying...
kubernetes_manifest.service: Destruction complete after 0s
kubernetes_manifest.service: Creating...

Error: Provider produced inconsistent result after apply

When applying changes to kubernetes_manifest.service, provider
"registry.terraform.io/hashicorp/kubernetes-alpha" produced an unexpected new
value: .object: wrong final value type: attribute "apiVersion": string
required.
```

I'm using the latest build of `terraform 0.14-dev`.

**Comment by cyberjacob** [comment] 2020-11-09 19:09
I believe the "wrong final value type" error is a known issue, that's being dealt with in #34

**Comment by dak1n1** [comment] 2020-11-12 20:15
I gave this another test today, after @alexsomesan explained how the server-side apply works. He was correct that the resource could indeed be deleted once the clusterIP was changed back to the original (immutable) value in the Terraform config. The issue is a limitation in Kubernetes server-side planning, where it fetches existing fields during the plan, which can sometimes lead to conflicts when merging them with new values (like the `clusterIP`).

```
$ grep clusterIP main.tf 
                        clusterIP = "10.96.3.11"

$ terraform show |grep clusterIP
            clusterIP      = "10.96.3.11"
            clusterIP             = "10.96.3.11"

$ terraform taint kubernetes_manifest.service
$ terraform apply --auto-approve
kubernetes_manifest.service: Refreshing state...
kubernetes_manifest.service: Destroying...
kubernetes_manifest.service: Destruction complete after 0s
kubernetes_manifest.service: Creating...
kubernetes_manifest.service: Creation complete after 0s

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

The best solution would be to use local planning, which is being worked on in #34 .

A work-around using server-side planning is to first delete the resource, then change the Terraform config to have the new value and re-create the resource using `terraform apply`. These are the only options currently available to us, so I'll close this issue to track it in #34 instead.

**Closed by dak1n1** 2020-11-12 20:15 UTC
Labels: acknowledged, bug
