### ISSUE TITLE
Applying Certmanager CRD throws errors 

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-provider-kubernetes-alpha#59] opened 2020-06-11 17:44 UTC
Description
using this repo try applying the certmanager crd and it throws these errors at me

```bash
git clone https://github.com/jrhouston/tfk8s.git
cd tfk8s/
make install
wget -c https://raw.githubusercontent.com/jetstack/cert-manager/release-0.13/deploy/manifests/00-crds.yaml


kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.13/deploy/manifests/00-crds.yaml

certificaterequests.cert-manager.io   2020-06-05T05:07:21Z
certificates.cert-manager.io          2020-06-05T05:07:21Z
challenges.acme.cert-manager.io       2020-06-05T05:07:21Z
clusterissuers.cert-manager.io        2020-06-05T05:07:21Z
issuers.cert-manager.io               2020-06-05T05:07:21Z
orders.acme.cert-manager.io           2020-06-05T05:07:21Z

kubectl get crd certificaterequests.cert-manager.io -o yaml |tfk8s -o certificaterequests.cert-manager.io.tf
kubectl get crd certificates.cert-manager.io -o yaml |tfk8s -o certificates.cert-manager.io.tf
kubectl get crd challenges.acme.cert-manager.io -o yaml |tfk8s -o challenges.acme.cert-manager.io.tf
kubectl get crd clusterissuers.cert-manager.io -o yaml |tfk8s -o clusterissuers.cert-manager.io.tf
kubectl get crd issuers.cert-manager.io  -o yaml |tfk8s -o issuers.cert-manager.io.tf
kubectl get crd orders.acme.cert-manager.io -o yaml  |tfk8s -o orders.acme.cert-manager.io.tf

cat certificaterequests.cert-manager.io.tf > 00-crds.tf
cat certificates.cert-manager.io.tf >> 00-crds.tf
cat challenges.acme.cert-manager.io.tf >> 00-crds.tf
cat clusterissuers.cert-manager.io.tf >> 00-crds.tf
cat issuers.cert-manager.io.tf >> 00-crds.tf
cat orders.acme.cert-manager.io.tf >> 00-crds.tf


kubectl delete crd  certificaterequests.cert-manager.io
kubectl delete crd certificates.cert-manager.io
kubectl delete crd challenges.acme.cert-manager.io
kubectl delete crd clusterissuers.cert-manager.io
kubectl delete crd issuers.cert-manager.io
kubectl delete crd orders.acme.cert-manager.io
# init
terraform init
terraform plan

```
![image](https://user-images.githubusercontent.com/981954/83844151-07a4c700-a6cc-11ea-86ac-c235768190bd.png)

this is how the crd is converted into hcl

![image](https://user-images.githubusercontent.com/981954/83844173-0f646b80-a6cc-11ea-806a-3c218e509422.png)

and there is the plugin
![image](https://user-images.githubusercontent.com/981954/83844183-168b7980-a6cc-11ea-9f73-898449d8c198.png)

the strangest thing is that before deleting the crd by hand with kubectl delete crd I tried the terraform plan and the plan came out like this
![image](https://user-images.githubusercontent.com/981954/83844523-c6f97d80-a6cc-11ea-9583-42dc8f781e7c.png)

I would appreciate it very much if you could help me

_Originally posted by @daverod24 in https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/51#issuecomment-639289008_

**Comment by daverod24** [comment] 2020-06-12 04:23
thanks @alexsomesan  i hope get help

**Comment by jan-eat** [comment] 2020-07-03 13:41
Had a look into it couldn't reproduce it unfortuntely, can you post your full `00-crds.tf` file?

What I did:
- Ran all the from `wget -c https://raw.githubusercontent.com/jetstack/cert-manager/release-0.13/deploy/manifests/00-crds.yaml` to `kubectl delete crd orders.acme.cert-manager.io`
- had to adjust the `00-crds.tf` file: add the provider, add `provider=kubernetes-alpha` to each resource. After running `plan`, I received `Error: rpc error: code = Unknown desc = update dry-run for '/orders.acme.cert-manager.io' failed: Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "orders.acme.cert-manager.io": uid mismatch: the provided object specified uid 2450fd39-0f12-4a47-a630-2cd86c207a38, and no existing object was found`, so I removed the `"uid"=..` entries from the tf file.
- after this, the CRDs deployed successfully.

My env:
`Terraform v0.12.26
+ provider.kubernetes-alpha (unversioned)`
and Kubernetes v1.17.6 on Google

In your picture above it appears like you're supplying lots of metadata - e.g. the `creationTimestamp`, `generation` and especially **`uid`**. I believe these should be automatically generated and might lead to conflicts if you set them yourself, did you try removing the metadata you don't need? What happens if you generate the .tf directly from the original yaml https://raw.githubusercontent.com/jetstack/cert-manager/release-0.13/deploy/manifests/00-crds.yaml instead of exporting the yamls through kubectl?

**Comment by modevops** [comment] 2020-12-10 17:56
I get similar error tying to apply a istio crd

```
Error: rpc error: code = Unknown desc = no matches for install.istio.io/v1alpha1, Resource=IstioOperator
```

A major use case for kube_manifest is crds and if we cannot do crds then what is the use for it? Can we add a flag for crds so that it does not try to validate kind in the manifest during terraform plan? We need this provider to be more dynamic. I really need this for crds.

We need hasicorp to provide a fix for this.  I hate using local-exec and  kube_manifest and tfk8s are perfect for this.  Fixing this would solve a lot issues in  building kubernetes cluster.  Please fix this asap we really need a solution for this whether it be a flag or another solution we needs this fixed. Having to use local exec or a script really sucks to do when kube_manifest was created to solve this exact problem.

**Closed** 2021-03-08 20:37 UTC
Labels: bug
